CREATE TYPE user_type AS ENUM (
  'charity',
  'creative'
);

CREATE TABLE cc_users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  user_type user_type,
  password TEXT NOT NULL,
  about TEXT,
  website TEXT
);

