CREATE TABLE cc_projects (
  id INTEGER primary key generated by default as identity,
  project_type TEXT NOT NULL,
  deadline TIMESTAMPTZ DEFAULT now() NOT NULL,
  deadline_flexibility TEXT NOT NULL,
  charity_id INTEGER REFERENCES cc_users(id),
  details TEXT
);